language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - yarn

script:
  - yarn run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pea3nut/finance-report:latest
  - docker push maolipeng/finance-report:latest
