language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - yarn

script:
  - yarn run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker build ./ -t maolipeng/finance-report:latest
  - docker push maolipeng/finance-report:latest
